In [1]:
import pandas as pd
import numpy as np

In [3]:
matrizA= np.array([[2, -3],
                   [4, -6],
                   [6,  9]])

In [4]:
matrizB = np.array([[1,  7],
                    [-3, 4],
                    [5, -8]])

In [10]:
somaAB = matrizA + matrizB
print(somaAB)

In [14]:
matrizC = np.array([[1,  5],
                    [3, -6],
                    [9,  3]])

matrizD = np.array([[4,  6,  3],
                    [-9, 10, 2]])

In [15]:
mutiplicacaoCD = np.dot(matrizC, matrizD)
print(mutiplicacaoCD)

[[-41  56  13]
 [ 66 -42  -3]
 [  9  84  33]]
